{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Week 4: In-Class Exercise - Data Filtering & Selection\n",
    "\n",
    "## Objective\n",
    "Practice filtering techniques using the same Education Statistics dataset you cleaned last week.\n",
    "\n",
    "## Time: ~30 minutes\n",
    "\n",
    "## What you'll practice:\n",
    "1. **Single conditions** with comparison operators\n",
    "2. **Combining conditions** with & (AND), | (OR), ~ (NOT)\n",
    "3. **Convenience methods**: .isin(), .between(), .str.contains()\n",
    "4. **Building real questions** from data\n",
    "\n",
    "## Dataset\n",
    "Same Education Statistics from the Colombian Ministry of Education (MEN) you cleaned in Week 3.\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Setup\n",
    "Run this cell to load libraries, load the dataset, and apply the quick clean from Week 3."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "i",
    "m",
    "p",
    "o",
    "r",
    "t",
    " ",
    "p",
    "a",
    "n",
    "d",
    "a",
    "s",
    " ",
    "a",
    "s",
    " ",
    "p",
    "d",
    "\n",
    "i",
    "m",
    "p",
    "o",
    "r",
    "t",
    " ",
    "n",
    "u",
    "m",
    "p",
    "y",
    " ",
    "a",
    "s",
    " ",
    "n",
    "p",
    "\n",
    "\n",
    "#",
    " ",
    "L",
    "o",
    "a",
    "d",
    " ",
    "t",
    "h",
    "e",
    " ",
    "E",
    "d",
    "u",
    "c",
    "a",
    "t",
    "i",
    "o",
    "n",
    " ",
    "S",
    "t",
    "a",
    "t",
    "i",
    "s",
    "t",
    "i",
    "c",
    "s",
    " ",
    "d",
    "a",
    "t",
    "a",
    "s",
    "e",
    "t",
    "\n",
    "d",
    "f",
    " ",
    "=",
    " ",
    "p",
    "d",
    ".",
    "r",
    "e",
    "a",
    "d",
    "_",
    "c",
    "s",
    "v",
    "(",
    "'",
    ".",
    ".",
    "/",
    "d",
    "a",
    "t",
    "a",
    "/",
    "e",
    "d",
    "u",
    "c",
    "a",
    "c",
    "i",
    "o",
    "n",
    "_",
    "e",
    "s",
    "t",
    "a",
    "d",
    "i",
    "s",
    "t",
    "i",
    "c",
    "a",
    "s",
    ".",
    "c",
    "s",
    "v",
    "'",
    ")",
    "\n",
    "\n",
    "#",
    " ",
    "Q",
    "u",
    "i",
    "c",
    "k",
    " ",
    "c",
    "l",
    "e",
    "a",
    "n",
    " ",
    "(",
    "a",
    "p",
    "p",
    "l",
    "y",
    "i",
    "n",
    "g",
    " ",
    "w",
    "h",
    "a",
    "t",
    " ",
    "w",
    "e",
    " ",
    "l",
    "e",
    "a",
    "r",
    "n",
    "e",
    "d",
    " ",
    "i",
    "n",
    " ",
    "W",
    "e",
    "e",
    "k",
    " ",
    "3",
    ")",
    "\n",
    "d",
    "f",
    "[",
    "'",
    "d",
    "e",
    "p",
    "a",
    "r",
    "t",
    "a",
    "m",
    "e",
    "n",
    "t",
    "o",
    "'",
    "]",
    " ",
    "=",
    " ",
    "d",
    "f",
    "[",
    "'",
    "d",
    "e",
    "p",
    "a",
    "r",
    "t",
    "a",
    "m",
    "e",
    "n",
    "t",
    "o",
    "'",
    "]",
    ".",
    "s",
    "t",
    "r",
    ".",
    "u",
    "p",
    "p",
    "e",
    "r",
    "(",
    ")",
    ".",
    "s",
    "t",
    "r",
    ".",
    "s",
    "t",
    "r",
    "i",
    "p",
    "(",
    ")",
    "\n",
    "d",
    "f",
    "[",
    "'",
    "a",
    "n",
    "o",
    "'",
    "]",
    " ",
    "=",
    " ",
    "d",
    "f",
    "[",
    "'",
    "a",
    "n",
    "o",
    "'",
    "]",
    ".",
    "f",
    "i",
    "l",
    "l",
    "n",
    "a",
    "(",
    "0",
    ")",
    ".",
    "a",
    "s",
    "t",
    "y",
    "p",
    "e",
    "(",
    "i",
    "n",
    "t",
    ")",
    "\n",
    "d",
    "f",
    " ",
    "=",
    " ",
    "d",
    "f",
    ".",
    "d",
    "r",
    "o",
    "p",
    "_",
    "d",
    "u",
    "p",
    "l",
    "i",
    "c",
    "a",
    "t",
    "e",
    "s",
    "(",
    ")",
    "\n",
    "d",
    "f",
    " ",
    "=",
    " ",
    "d",
    "f",
    ".",
    "d",
    "r",
    "o",
    "p",
    "n",
    "a",
    "(",
    "s",
    "u",
    "b",
    "s",
    "e",
    "t",
    "=",
    "[",
    "'",
    "d",
    "e",
    "p",
    "a",
    "r",
    "t",
    "a",
    "m",
    "e",
    "n",
    "t",
    "o",
    "'",
    "]",
    ")",
    "\n",
    "\n",
    "p",
    "r",
    "i",
    "n",
    "t",
    "(",
    "f",
    "\"",
    "D",
    "a",
    "t",
    "a",
    "s",
    "e",
    "t",
    " ",
    "l",
    "o",
    "a",
    "d",
    "e",
    "d",
    " ",
    "a",
    "n",
    "d",
    " ",
    "c",
    "l",
    "e",
    "a",
    "n",
    "e",
    "d",
    ":",
    " ",
    "{",
    "d",
    "f",
    ".",
    "s",
    "h",
    "a",
    "p",
    "e",
    "[",
    "0",
    "]",
    "}",
    " ",
    "r",
    "o",
    "w",
    "s",
    ",",
    " ",
    "{",
    "d",
    "f",
    ".",
    "s",
    "h",
    "a",
    "p",
    "e",
    "[",
    "1",
    "]",
    "}",
    " ",
    "c",
    "o",
    "l",
    "u",
    "m",
    "n",
    "s",
    "\"",
    ")",
    "\n",
    "p",
    "r",
    "i",
    "n",
    "t",
    "(",
    "f",
    "\"",
    "Y",
    "e",
    "a",
    "r",
    "s",
    ":",
    " ",
    "{",
    "s",
    "o",
    "r",
    "t",
    "e",
    "d",
    "(",
    "d",
    "f",
    "[",
    "'",
    "a",
    "n",
    "o",
    "'",
    "]",
    ".",
    "u",
    "n",
    "i",
    "q",
    "u",
    "e",
    "(",
    ")",
    ")",
    "}",
    "\"",
    ")",
    "\n",
    "p",
    "r",
    "i",
    "n",
    "t",
    "(",
    "f",
    "\"",
    "D",
    "e",
    "p",
    "a",
    "r",
    "t",
    "m",
    "e",
    "n",
    "t",
    "s",
    ":",
    " ",
    "{",
    "d",
    "f",
    "[",
    "'",
    "d",
    "e",
    "p",
    "a",
    "r",
    "t",
    "a",
    "m",
    "e",
    "n",
    "t",
    "o",
    "'",
    "]",
    ".",
    "n",
    "u",
    "n",
    "i",
    "q",
    "u",
    "e",
    "(",
    ")",
    "}",
    " ",
    "u",
    "n",
    "i",
    "q",
    "u",
    "e",
    "\"",
    ")",
    "\n",
    "d",
    "f",
    ".",
    "h",
    "e",
    "a",
    "d",
    "(",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 1: Single Conditions (8 minutes)\n",
    "\n",
    "Start with simple, one-condition filters using comparison operators."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 1.1: Filter by exact value\n",
    "Get all rows where the year (`ano`) is 2023.\n",
    "\n",
    "**Pattern:** `df[df['column'] == value]`\n",
    "\n",
    "Print how many rows you found."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n",
    "# Step 1: Create the filter\n",
    "# Step 2: Print the number of rows\n",
    "# Step 3: Display the first few rows\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 1.2: Filter with greater than\n",
    "Find all rows where the total dropout rate (`desercion`) is greater than 5%.\n",
    "\n",
    "**Question:** How many department-year combinations have a dropout rate above 5%?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 1.3: Filter with less than\n",
    "Find all rows where net coverage (`cobertura_neta`) is less than 70%.\n",
    "\n",
    "**Question:** Which departments have the lowest coverage? Look at the `departamento` column in your result."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 2: Combining Conditions (8 minutes)\n",
    "\n",
    "Now combine multiple conditions using `&` (AND), `|` (OR), and `~` (NOT).\n",
    "\n",
    "**Remember:** Always wrap each condition in parentheses!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 2.1: AND condition\n",
    "Find rows where the year is 2023 AND the dropout rate is above 5%.\n",
    "\n",
    "**Pattern:** `df[(condition1) & (condition2)]`\n",
    "\n",
    "**Question:** Which departments had high dropout in 2023?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n",
    "# Show: departamento, ano, desercion columns\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 2.2: OR condition\n",
    "Find all rows from either Antioquia OR Valle del Cauca.\n",
    "\n",
    "**Pattern:** `df[(condition1) | (condition2)]`\n",
    "\n",
    "**Hint:** The department names should be uppercase (we cleaned them in setup)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 2.3: NOT condition\n",
    "Get all rows EXCEPT those from the \"NACIONAL\" department (the national aggregate).\n",
    "\n",
    "**Two ways to do this:**\n",
    "- `df[df['departamento'] != 'NACIONAL']`\n",
    "- `df[~(df['departamento'] == 'NACIONAL')]`\n",
    "\n",
    "Try both and verify you get the same number of rows."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n",
    "# Method 1: using !=\n",
    "\n",
    "# Method 2: using ~\n",
    "\n",
    "# Compare the row counts\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 3: Convenience Methods (7 minutes)\n",
    "\n",
    "Use `.isin()`, `.between()`, and `.str.contains()` to write cleaner filters."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 3.1: .isin() - Match a list\n",
    "Find all rows from the following departments: ANTIOQUIA, BOGOTA D.C., VALLE DEL CAUCA, CUNDINAMARCA.\n",
    "\n",
    "**Pattern:** `df[df['column'].isin([list_of_values])]`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 3.2: .between() - Numeric range\n",
    "Find all rows where the approval rate (`aprobacion`) is between 90 and 100 (inclusive).\n",
    "\n",
    "**Pattern:** `df[df['column'].between(low, high)]`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 3.3: .str.contains() - Text pattern\n",
    "Find all rows where the department name contains \"SANTANDER\".\n",
    "\n",
    "**Pattern:** `df[df['column'].str.contains('text', na=False)]`\n",
    "\n",
    "**Question:** Which departments match? (Hint: there should be more than one.)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n",
    "# Print the unique department names in your result\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 4: Real Questions (5 minutes)\n",
    "\n",
    "Use everything you've learned to answer these questions about the data."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 4.1: Complex filter\n",
    "Find departments in 2023 where:\n",
    "- Net coverage is above 80% AND\n",
    "- Dropout rate is below 3%\n",
    "\n",
    "These are the \"high performing\" departments. Show the department name, coverage, and dropout columns."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Task 4.2: Try .query()\n",
    "Rewrite the filter from Task 4.1 using `.query()` instead of boolean indexing.\n",
    "\n",
    "**Pattern:** `df.query('condition1 and condition2')`\n",
    "\n",
    "Verify you get the same number of rows."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR CODE HERE\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Bonus: Design Your Own Filter (if time permits)\n",
    "\n",
    "Think of a question you could ask about the education data. Write the filter to answer it.\n",
    "\n",
    "Example questions:\n",
    "- Which departments had improving dropout rates (2022 lower than 2020)?\n",
    "- Which departments in the Llanos region (Arauca, Casanare, Meta, Vichada) have the best coverage?\n",
    "- What was the range of approval rates in 2024?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# YOUR QUESTION: ________________________________\n",
    "# YOUR CODE HERE\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Summary\n",
    "\n",
    "In this exercise you practiced:\n",
    "\n",
    "1. **Single conditions** - `==`, `!=`, `>`, `<`, `>=`, `<=`\n",
    "2. **Combining conditions** - `&` (AND), `|` (OR), `~` (NOT)\n",
    "3. **Convenience methods** - `.isin()`, `.between()`, `.str.contains()`\n",
    "4. **Clean syntax** - `.query()` as an alternative\n",
    "\n",
    "Key rules:\n",
    "- Use `&` `|` `~` (NOT `and` `or` `not`) for DataFrames\n",
    "- Always wrap conditions in **parentheses**\n",
    "- Add `na=False` to `.str.contains()`\n",
    "\n",
    "**Next:** Complete the workshop notebook for more complex filtering scenarios and analysis."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}